name: List LAVA test jobs for subsequent steps
inputs:
  prefix:
    description: Test job name prefix. Will be used for searching .yaml files
    required: true
outputs:
  jobmatrix:
    description: Job matrix composed from downloaded LAVA test job files
    value: ${{ steps.listjobs.outputs.jobmatrix }}
runs:
  using: "composite"
  steps:
    - name: "List jobs"
      id: listjobs
      shell: bash
      run: |
        JOBFILES=$(find . -name "${{ inputs.prefix }}*.yaml")
        RESULT_JSON=$(jq -n '{target: []}')
        for J in $JOBFILES
          do
              echo $J
              J_TMP="${J#*-}"
              NAME="${J_TMP%%/*}"
              echo $NAME
              F_TMP="${J#*/}"
              RESULT_NAME="${F_TMP//\//-}"
              echo $RESULT_NAME
              RESULT_JSON=$(echo "$RESULT_JSON" | jq -c --arg path "${J}" --arg result_file "${RESULT_NAME}" --arg name "${NAME}" '.target += [$ARGS.named]')
              echo "$RESULT_JSON"
          done
          echo "$RESULT_JSON"

        echo "jobmatrix=$RESULT_JSON" >> $GITHUB_OUTPUT
        echo "Preparing testjob files"

