name: Run lava-test-plans
inputs:
  machines:
    description: "Comma separated list of machines"
    required: true
  distro_name:
    description: "Name of the distro including kernel suffix"
    required: true
  build_id:
    description: "ID of the workflow from which build URL will be downloaded"
    required: true
  gh_token:
    description: "Github token. It's required to download artifacts from the workflow"
    required: true
  prefix:
    description: "Prefix for the compressed file that is uploaded as workflow artifact"
    default: testjobs
  testplan:
    description: "Name of the test plan to use in job generation"
    default: boot

outputs:
  jobmatrix:
    description: Job matrix composed from generated LAVA test job files
    value: ${{ steps.lava-test-plans.outputs.jobmatrix }}

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
        with:
          repository: qualcomm-linux/lava-test-plans
          path: lava-test-plans
          ref: 5cb21d587827192e6bd1e601d461c8e326c545db

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: 'Download build URLs'
        uses: actions/download-artifact@v7
        with:
          github-token: ${{ inputs.gh_token }}
          run-id: ${{ inputs.build_id }}
          pattern: build-url_*_${{ inputs.distro_name }}

      - name: Run lava-test-plans
        id: lava-test-plans
        shell: bash
        run: |
          set -euo pipefail
          cd lava-test-plans && pip install .
          lava-test-plans --version
          OUT_PATH="${GITHUB_WORKSPACE}/out"
          VARS_OUT_PATH="${OUT_PATH}/vars"
          JOBS_OUT_PATH="${OUT_PATH}/jobs"
          echo "JOBS_OUT_PATH=${JOBS_OUT_PATH}" >> $GITHUB_ENV
          mkdir -p "${VARS_OUT_PATH}"
          mkdir -p "${JOBS_OUT_PATH}"
          #echo "PROJECT_NAME=${GITHUB_REPOSITORY#*/}" >> "${VARS_OUT_PATH}/gh-variables.ini"
          #echo "PROJECT=projects/${GITHUB_REPOSITORY#*/}/" >> "${VARS_OUT_PATH}/gh-variables.ini"
          echo "PROJECT_NAME=meta-qcom" >> "${VARS_OUT_PATH}/gh-variables.ini"
          echo "PROJECT=projects/meta-qcom/" >> "${VARS_OUT_PATH}/gh-variables.ini"
          echo "LAVA_JOB_PRIORITY=50" >> "${VARS_OUT_PATH}/gh-variables.ini"
          # OS_INFO can be omited
          echo "OS_INFO=qcom-distro" >> "${VARS_OUT_PATH}/gh-variables.ini"
          echo "AUDIO_CLIPS_BASE_DIR=/home/AudioClips/" >> "${VARS_OUT_PATH}/gh-variables.ini"
          echo "BUILD_NUMBER=${{ github.run_id }}-${{ github.run_attempt }}" >> "${VARS_OUT_PATH}/gh-variables.ini"
          echo "DOCKER_IMAGE_POSTPROCESS=ghcr.io/foundriesio/lava-lmp-sign:main" >> "${VARS_OUT_PATH}/gh-variables.ini"
          echo "AUTH_HEADER_NAME=Authorization" >> "${VARS_OUT_PATH}/gh-variables.ini"
          echo "AUTH_HEADER_TOKEN=Q_S3_TOKEN" >> "${VARS_OUT_PATH}/gh-variables.ini"
          echo "TEST_DEFINITIONS_REPOSITORY=https://github.com/qualcomm-linux/qcom-linux-testkit/" >> "${VARS_OUT_PATH}/gh-variables.ini"
          IMAGE_TYPE="core-image-base"
          case "${{ inputs.distro_name }}" in
            "qcom-distro"*)
              IMAGE_TYPE="qcom-multimedia-image"
              echo "AUTO_LOGIN_PASSWORD_PROMPT=Password" >> "${VARS_OUT_PATH}/gh-variables.ini"
              echo "AUTO_LOGIN_PASSWORD=oelinux123" >> "${VARS_OUT_PATH}/gh-variables.ini"
              ;;
          esac

          OLDIFS=$IFS
          IFS=,
          for machine in ${{ inputs.machines }}; do
            echo "Rendering test job templates for ${machine}"
            cp "${VARS_OUT_PATH}/gh-variables.ini" "${machine}.ini"
            echo "IMAGE_FILE_NAME=${IMAGE_TYPE}-${machine}.rootfs.qcomflash.tar.gz" >> "${machine}.ini"
            echo "DEVICE_TYPE=${machine}" >> "${machine}.ini"
            export BUILD_URL=""
            export BUILD_URL_FILE="$GITHUB_WORKSPACE/build-url_${machine}_${{ inputs.distro_name }}"
            echo "${BUILD_URL_FILE}"
            if [ -f "$BUILD_URL_FILE" ]; then
                export BUILD_URL=$(cat "${BUILD_URL_FILE}")
            fi
            if [ -z "${BUILD_URL}" ]; then
               echo "BUILD_URL missing"
               # fail action if BUILD_URL is empty. At this point the variable should be filled in
               continue
            fi
            echo "BUILD_DOWNLOAD_URL=${BUILD_URL}/" >> "${VARS_OUT_PATH}/gh-variables.ini"

            echo "ROOTFS_URL=${BUILD_URL}/${{ inputs.distro_name }}/${machine}/${IMAGE_TYPE}-${machine}.rootfs.qcomflash.tar.gz" >> "${VARS_OUT_PATH}/gh-variables.ini"

            if [ "${machine}" = "dragonboard-410c" ]; then
                echo "ROOTFS_IMG_FILE=${IMAGE_TYPE}-qcom-armv8a.rootfs.ext4" >> "${machine}.ini"
                echo "BOOT_IMG_FILE=boot-apq8016-sbc-qcom-armv8a.img" >> "${machine}.ini"
                echo "BUILD_OS=${{ inputs.distro_name }}${{ inputs.kernel }}/" >> "${machine}.ini"
            fi
            if [ "${machine}" = "dragonboard-820c" ]; then
                echo "ROOTFS_IMG_FILE=${IMAGE_TYPE}-qcom-armv8a.rootfs.ext4" >> "${machine}.ini"
                echo "BOOT_IMG_FILE=boot-apq8096-db820c-qcom-armv8a.img" >> "${machine}.ini"
                echo "BUILD_OS=${{ inputs.distro_name }}${{ inputs.kernel }}/" >> "${machine}.ini"
            fi

            cat "${machine}.ini"
            #lava-test-plans --dry-run --variables "${VARS_OUT_PATH}/gh-variables.ini" --test-plan "${GITHUB_REPOSITORY#*/}/${{ inputs.distro_name }}/${{ inputs.testplan }}" --device-type "projects/${GITHUB_REPOSITORY#*/}/devices/${{ inputs.machine }}" --dry-run-path "${JOBS_OUT_PATH}/${{ inputs.machine }}-${{ inputs.distro_name }}${{ inputs.kernel }}-${{ inputs.testplan }}" || true
            lava-test-plans --dry-run --variables "${machine}.ini" --test-plan "meta-qcom/${{ inputs.distro_name }}/${{ inputs.testplan }}" --device-type "projects/meta-qcom/devices/${machine}" --dry-run-path "${JOBS_OUT_PATH}/${machine}-${{ inputs.distro_name }}-${{ inputs.testplan }}" || true
            # create the JSON file that is used for the job submission matrix
          done

          #RESULT_JSON=$(jq -n '{target: []}')
          #echo "jobmatrix=$RESULT_JSON" >> $GITHUB_OUTPUT

#      - name: "List files"
#        shell: bash
#        run: |
#          echo "${GITHUB_WORKSPACE}"
#          ls -R "${GITHUB_WORKSPACE}"

      - name: 'Upload test jobs'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.prefix }}-${{ inputs.distro_name }}${{ inputs.kernel }}
          path: ${{ env.JOBS_OUT_PATH }}/**

