name: LAVA jobs schema check

on:
  workflow_call:

jobs:
  schema-check:
    runs-on: ubuntu-latest
    container: lavasoftware/lava-server
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Schema check
        run: |
          MACHINE="foo"
          DOWNLOADS_URL="https://bar.com"
          find lava/ -name "*.yaml" -exec sed -i "s|{{ DOWNLOADS_URL }}|${DOWNLOADS_URL}|g" '{}' \;
          find lava/ -name "*.yaml" -exec sed -i "s|{{ MACHINE }}|${MACHINE}|g" '{}' \;
          tee -a schemacheck.py <<EOF
          import sys
          import yaml
          from lava_common.schema import *
          try:
            f = open(sys.argv[1], "rb")
            y = yaml.safe_load(f)
            validate(y)
          except:
            sys.exit(1)
          sys.exit(0)
          EOF
          find lava/ -name "*.yaml" -exec python3 schemacheck.py '{}' \;



