name: LAVA jobs schema check

on:
  workflow_call:

jobs:
  schema-check:
    runs-on: ubuntu-latest
    container: lavasoftware/lava-server
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Schema check
        run: |
          MACHINE="foo"
          DOWNLOADS_URL="https://bar.com"
          find lava/ -name "*.yaml" -exec sed -i "s|{{ DOWNLOADS_URL }}|${DOWNLOADS_URL}|g" '{}' \;
          find lava/ -name "*.yaml" -exec sed -i "s|{{ MACHINE }}|${MACHINE}|g" '{}' \;
          python3 schemacheck.py



