name: Build on PR

on:
  pull_request:

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}
  schema-check:
    uses: ./.github/workflows/lava-sanity.yml
  nightly:
    uses: ./.github/workflows/build.yml
