name: Run tests

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  retrieve-job-list:
    outputs:
      jobmatrix: ${{ steps.listjobs.outputs.jobmatrix }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: testjobs
          path: lava/
      - name: Print trigger
        run: |
          echo "Triggered by ${{ github.event_name }}"
          echo "Triggering workflow: ${{ github.event.workflow_run.id }}"
      - name: "List jobs"
        id: listjobs
        run: |
          JOBFILES=$(find lava/ -name *.yaml)
          JOBFILES=$(echo "$JOBFILES" | sed -e "s/^/\"/" | sed -e "s/$/\",/" | tr -d "\n" | sed -e "s/.$//")
          JOBFILES="[${JOBFILES}]"
          J=$(jq -cn --argjson jobfiles "$JOBFILES" '{target: $jobfiles}')
          echo "jobmatrix=$J" >> $GITHUB_OUTPUT
    runs-on: ubuntu-latest
  submit-job:
    needs: retrieve-job-list
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.retrieve-job-list.outputs.jobmatrix) }}
    steps:
      - name: 'Download Artifacts ${{ matrix.target }}'
        uses: actions/download-artifact@v4
        timeout-minutes: 20
        with:
          name: testjobs
          path: lava/

      - name: Submit ${{ matrix.target }}
        run: |
          echo "Submitting ${{ matrix.target }}"

