name: Tests

on:
  workflow_call:
    inputs:
      build_id:
        required: true
        type: string
    outputs:
      summary_id:
        description: "ID of the test summary artifact"
        value: ${{ jobs.publish-test-summary.outputs.summary_id }}

jobs:
  boot-test-nodistro:
    uses: ./.github/workflows/test-distro.yml
    runs-on: ubuntu-latest
    with:
      build_id: ${{ inputs.build_id }}
      devices: "iq-8275-evk,iq-9075-evk,qcm6490-idp,qcs615-ride,rb3gen2-core-kit,qcs8300-ride-sx,qcs9100-ride-sx,dragonboard-410c,dragonboard-820c,rb1-core-kit"
      distro: "nodistro"
  boot-test-qcom-distro:
    uses: ./.github/workflows/test-distro.yml
    runs-on: ubuntu-latest
    with:
      build_id: ${{ inputs.build_id }}
      devices: "iq-8275-evk,iq-9075-evk,qcm6490-idp,qcs615-ride,rb3gen2-core-kit,qcs8300-ride-sx,qcs9100-ride-sx,dragonboard-410c,dragonboard-820c,rb1-core-kit"
      distro: "qcom-distro"
  boot-test-qcom-distro_linux-qcom-6.18:
    uses: ./.github/workflows/test-distro.yml
    runs-on: ubuntu-latest
    with:
      build_id: ${{ inputs.build_id }}
      devices: "iq-8275-evk,iq-9075-evk,qcm6490-idp,qcs615-ride,rb3gen2-core-kit,qcs8300-ride-sx,qcs9100-ride-sx,dragonboard-410c,dragonboard-820c,rb1-core-kit"
      distro: "qcom-distro_linux-qcom-6.18"
#
#  prepare-premerge-jobs:
#    needs: boot-job-result
#    # run only if boot jobs are successful
#    if: ${{ needs.boot-job-result.outputs.boot_result == 'success' }}
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        # only run pre-merge tests on devices available in the LAB
#        # and "contemporary" - exclude dragonboards
#        machine:
#          #- iq-9075-evk
#          - qcs615-ride
#          #- rb3gen2-core-kit
#          #- qcs8300-ride-sx
#          #- qcs9100-ride-sx
#          #- rb1-core-kit
#        distro:
#          - name: poky-altcfg
#          - name: qcom-distro
#        kernel:
#          - ""
#          - -linux-qcom-6.18
#        exclude:
#          - distro: poky-altcfg
#            kernel: _linux-qcom-6.18
#    steps:
#      - id: print-condition
#        name: "Print condition"
#        env:
#          RESULT: ${{ needs.boot-job-result.outputs.boot_result }}
#        run: |
#          echo "${RESULT}"
#
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - name: Run lava-test-plans
#        uses: ./.github/actions/lava-test-plans
#        with:
#          machine: ${{ matrix.machine }}
#          distro_name: ${{ matrix.distro.name }}
#          kernel: ${{ matrix.kernel }}
#          build_id: ${{ inputs.build_id }}
#          gh_token: ${{ secrets.GITHUB_TOKEN }}
#          prefix: premerge
#          testplan: pre-merge
#
#  prepare-premerge-job-list:
#    needs: prepare-premerge-jobs
#    runs-on: ubuntu-latest
#    outputs:
#      jobmatrix: ${{ steps.listjobs.outputs.jobmatrix }}
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - name: "List jobs"
#        id: listjobs
#        uses: ./.github/actions/list-jobs
#        with:
#          prefix: "premerge"
#          build_id: ${{ github.run_id }}
#          gh_token: ${{ secrets.GITHUB_TOKEN }}
#
#  submit-premerge-job:
#    needs: prepare-premerge-job-list
#    runs-on: ubuntu-latest
#    continue-on-error: true
#    name: Pre-merge ${{ matrix.target.name }}
#    strategy:
#      matrix: ${{ fromJson(needs.prepare-premerge-job-list.outputs.jobmatrix) }}
#    steps:
#      - name: 'Download job templates'
#        uses: actions/download-artifact@v7
#        with:
#          name: ${{ matrix.target.artifact}}
#
#      - name: Submit ${{ matrix.target.name }}
#        timeout-minutes: 20
#        uses: foundriesio/lava-action@v9
#        with:
#          #lava_token: ${{ secrets.LAVA_TOKEN }}
#          lava_token: ${{ secrets.LAVA_STAGING_TOKEN }}
#          #lava_url: 'lava.infra.foundries.io'
#          lava_url: 'lava-staging.infra.foundries.io'
#          job_definition: ${{ matrix.target.path }}
#          wait_for_job: true
#          fail_action_on_failure: true
#          fail_action_on_incomplete: true
#          save_result_as_artifact: true
#          save_job_details: true
#          result_file_name: "${{ matrix.target.result_file }}"

  publish-test-summary:
    name: "Publish Tests Summary"
    #needs: [submit-premerge-job, submit-boot-job]
    needs: [boot-test-nodistro, boot-test-qcom-distro, boot-test-qcom-distro_linux-qcom-6.18]
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    outputs:
      summary_id: ${{ steps.generate-summary.outputs.artifact_id }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Summary
        id: generate-summary
        uses: ./.github/actions/test-job-summary
        with:
          build_id: ${{ github.run_id }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          summary_file_name: test_job_summary

      - name: Download Summary
        uses: actions/download-artifact@v7
        with:
          artifact-ids: ${{ steps.generate-summary.outputs.artifact_id }}

      - name: Publish Test Job Details
        run: |
            cat test_job_summary >> $GITHUB_STEP_SUMMARY
