name: Run tests

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
jobs:
  retrieve-job-list:
    outputs:
      jobmatrix: ${{ steps.listjobs.outputs.jobmatrix }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Print trigger
        run: |
          echo "Triggered by ${{ github.event_name }}"
          echo "Input: ${{ inputs.url }}"
      - name: "List jobs"
        id: listjobs
        run: |
          find lava/ -name "*.yaml" -exec sed -i "s|{{ DOWNLOADS_URL }}|${{inputs.url}}|g" '{}' \;
          JOBFILES=$(find lava/ -name *.yaml)
          JOBFILES=$(echo "$JOBFILES" | sed -e "s/^/\"/" | sed -e "s/$/\",/" | tr -d "\n" | sed -e "s/.$//")
          JOBFILES="[${JOBFILES}]"
          J=$(jq -cn --argjson jobfiles "$JOBFILES" '{target: $jobfiles}')
          echo "jobmatrix=$J" >> $GITHUB_OUTPUT
          echo "Preparing testjob files"
      - name: 'Upload test jobs'
        uses: actions/upload-artifact@v4
        with:
          name: testjobs
          path: lava/
    runs-on: ubuntu-latest
  submit-job:
    needs: retrieve-job-list
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.retrieve-job-list.outputs.jobmatrix) }}
    steps:
      - name: 'Download Artifacts ${{ matrix.target }}'
        uses: actions/download-artifact@v4
        with:
          name: testjobs
          path: lava/
      - name: "Update test names"
        run: |
          PATH=$(echo "${{ matrix.target }}" | awk -F/ '{print $2"/"$3}')
          MACHINE=$(echo "${{ matrix.target }}" | awk -F/ '{print $2}')
          FIND_PATH=$()
          find "${FIND_PATH}" -name "*.yaml" -exec sed -i "s|{{ MACHINE }}|${MACHINE}|g" '{}' \;

      - name: Submit ${{ matrix.target }}
        timeout-minutes: 20
        uses: foundriesio/lava-action@v3
        with:
          lava_token: ${{ secrets.LAVA_TOKEN }}
          lava_url: 'lava.infra.foundries.io'
          job_definition: ${{ matrix.target }}
          wait_for_job: 'true'
          fail_action_on_failure: 'true'

