name: Run tests

on:
  workflow_call:
    inputs:
      build_id:
        required: true
        type: string

jobs:
  retrieve-job-list:
    outputs:
      jobmatrix: ${{ steps.listjobs.outputs.jobmatrix }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Print trigger
        run: |
          echo "Triggered by ${{ github.event_name }}"
      - name: "List jobs"
        id: listjobs
        run: |
          JOBFILES=$(find lava/ -name *.yaml)
          JOBFILES=$(echo "$JOBFILES" | sed -e "s/^/\"/" | sed -e "s/$/\",/" | tr -d "\n" | sed -e "s/.$//")
          JOBFILES="[${JOBFILES}]"
          J=$(jq -cn --argjson jobfiles "$JOBFILES" '{target: $jobfiles}')
          echo "jobmatrix=$J" >> $GITHUB_OUTPUT
          echo "Preparing testjob files"
      - name: 'Upload test jobs'
        uses: actions/upload-artifact@v4
        with:
          name: testjobs
          path: lava/
    runs-on: ubuntu-latest
  submit-job:
    needs: retrieve-job-list
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.retrieve-job-list.outputs.jobmatrix) }}
    steps:
      - name: 'Download job templates'
        uses: actions/download-artifact@v4
        with:
          name: testjobs
          path: lava/
      - name: 'Download build URLs'
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.build_id }}
          pattern: build_url-*

      - name: "Update test names"
        run: |
          TARGET=${{ matrix.target }}
          FIND_PATH="${TARGET#*/}"
          MACHINE="${FIND_PATH%/*}"
          if [ -d "build_url-${MACHINE}" ]; then
              BASE_ARTIFACT_URL=$(cat "build_url-${MACHINE}/build_url-${MACHINE}")
          else
              # fail the job because of missing URL file
              ls -l
              echo "Build URL file build_url-${MACHINE} is missing"
              exit 1
          fi
          FILE_NAME=$(echo "${FIND_PATH%.yaml}" | tr "/" "-")
          find "${{ matrix.target }}" -name "*.yaml" -exec sed -i "s|{{ MACHINE }}|${MACHINE}|g" '{}' \;
          find "${{ matrix.target }}" -name "*.yaml" -exec sed -i "s|{{ AP_NAME }}|${{secrets.AP_NAME}}|g" '{}' \;
          find "${{ matrix.target }}" -name "*.yaml" -exec sed -i "s|{{ AP_PASSWORD }}|${{secrets.AP_PASSWORD}}|g" '{}' \;
          find "${{ matrix.target }}" -name "*.yaml" -exec sed -i "s|{{ DOWNLOADS_URL }}|${BASE_ARTIFACT_URL}|g" '{}' \;
          cat "${{ matrix.target }}"
          echo "MACHINE=${FILE_NAME}" >> $GITHUB_ENV

      - name: Submit ${{ matrix.target }}
        env:
          MACHINE: ${{ env.MACHINE }}
        timeout-minutes: 20
        uses: foundriesio/lava-action@v8
        with:
          lava_token: ${{ secrets.LAVA_TOKEN }}
          lava_url: 'lava.infra.foundries.io'
          job_definition: ${{ matrix.target }}
          wait_for_job: true
          fail_action_on_failure: false
          fail_action_on_incomplete: false
          save_result_as_artifact: true
          save_job_details: true
          result_file_name: "${{ env.MACHINE }}"

  publish-test-results:
    name: "Publish Tests Results"
    needs: submit-job
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: "List files"
        run: |
          echo $GITHUB_WORKSPACE
          ls -R $GITHUB_WORKSPACE

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "${{ github.workspace }}/artifacts/**/*.xml"

      - name: Publish Test Job Details
        run: |
          for json_file in $(find ${{ github.workspace }} -name "test-job-*.json")
          do
              DEVICE_TYPE=$(cat "$json_file" | jq -r ".requested_device_type")
              URL=$(cat "$json_file" | jq -r ".url")
              JOB_ID=$(cat "$json_file" | jq -r ".id")
              echo " * [Job $JOB_ID on $DEVICE_TYPE]($URL)"
              echo " * [Job $JOB_ID on $DEVICE_TYPE]($URL)" >> $GITHUB_STEP_SUMMARY
          done

