name: On Workflow run tests

on:
  workflow_run:
    workflows: ["Build on PR"]
    types:
      - completed

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    with:
      url: ${{ github.event.workflow_run.outputs.artifacts_url }}
